// Date: 8/9/2013 8:07:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package claycorp.soggycarpet.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBear extends ModelBase {
    // fields
    ModelRenderer snout;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer ear1;
    ModelRenderer ear2;

    public ModelBear() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.snout = new ModelRenderer(this, 0, 30);
        this.snout.addBox(0F, 0F, 0F, 4, 4, 4);
        this.snout.setRotationPoint(-2F, 8F, -18F);
        this.snout.setTextureSize(128, 64);
        this.snout.mirror = true;
        this.setRotation(this.snout, 0F, 0F, 0F);
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-3F, -4F, -6F, 8, 8, 6);
        this.head.setRotationPoint(-1F, 9F, -8F);
        this.head.setTextureSize(128, 64);
        this.head.mirror = true;
        this.setRotation(this.head, 0F, 0F, 0F);
        this.body = new ModelRenderer(this, 18, 4);
        this.body.addBox(-6F, -10F, -7F, 18, 23, 15);
        this.body.setRotationPoint(-3F, 10F, 2F);
        this.body.setTextureSize(128, 64);
        this.body.mirror = true;
        this.setRotation(this.body, 1.570796F, 0F, 0F);
        this.leg1 = new ModelRenderer(this, 0, 16);
        this.leg1.addBox(-3F, 0F, -2F, 4, 7, 4);
        this.leg1.setRotationPoint(-5F, 17F, 12F);
        this.leg1.setTextureSize(128, 64);
        this.leg1.mirror = true;
        this.setRotation(this.leg1, 0F, 0F, 0F);
        this.leg2 = new ModelRenderer(this, 0, 16);
        this.leg2.addBox(1F, 0F, 1F, 4, 7, 4);
        this.leg2.setRotationPoint(3F, 17F, 9F);
        this.leg2.setTextureSize(128, 64);
        this.leg2.mirror = true;
        this.setRotation(this.leg2, 0F, 0F, 0F);
        this.leg3 = new ModelRenderer(this, 0, 16);
        this.leg3.addBox(-5F, 0F, -3F, 4, 7, 4);
        this.leg3.setRotationPoint(-3F, 17F, -5F);
        this.leg3.setTextureSize(128, 64);
        this.leg3.mirror = true;
        this.setRotation(this.leg3, 0F, 0F, 0F);
        this.leg4 = new ModelRenderer(this, 0, 16);
        this.leg4.addBox(1F, 0F, -3F, 4, 7, 4);
        this.leg4.setRotationPoint(3F, 17F, -5F);
        this.leg4.setTextureSize(128, 64);
        this.leg4.mirror = true;
        this.setRotation(this.leg4, 0F, 0F, 0F);
        this.ear1 = new ModelRenderer(this, 22, 0);
        this.ear1.addBox(-3.5F, -1.5F, -7.5F, 1, 1, 1);
        this.ear1.setRotationPoint(-1F, 6F, -7F);
        this.ear1.setTextureSize(128, 64);
        this.ear1.mirror = true;
        this.setRotation(this.ear1, 0F, 0F, 0F);
        this.ear2 = new ModelRenderer(this, 22, 0);
        this.ear2.addBox(4F, -4F, -4F, 1, 1, 1);
        this.ear2.setRotationPoint(-0.5F, 8.5F, -10.5F);
        this.ear2.setTextureSize(128, 64);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, 0F, 0F, 0F);
    }

    @Override
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.snout.render(f5);
        this.head.render(f5);
        this.body.render(f5);
        this.leg1.render(f5);
        this.leg2.render(f5);
        this.leg3.render(f5);
        this.leg4.render(f5);
        this.ear1.render(f5);
        this.ear2.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        this.head.rotateAngleX = f5 / (180F / (float)Math.PI);
        this.head.rotateAngleY = f4 / (180F / (float)Math.PI);
        this.snout.rotateAngleX = this.head.rotateAngleX;
        this.snout.rotateAngleY = this.head.rotateAngleY;
        this.ear1.rotateAngleX = this.head.rotateAngleX;
        this.ear1.rotateAngleY = this.head.rotateAngleY;
        this.ear2.rotateAngleX = this.head.rotateAngleX;
        this.ear2.rotateAngleY = this.head.rotateAngleY;
        this.body.rotateAngleX = ((float)Math.PI / 2F);
        this.leg1.rotateAngleX = MathHelper.cos(f1 * 0.6662F) * 1.4F * f2;
        this.leg2.rotateAngleX = MathHelper.cos(f1 * 0.6662F + (float)Math.PI) * 1.4F * f2;
        this.leg3.rotateAngleX = MathHelper.cos(f1 * 0.6662F + (float)Math.PI) * 1.4F * f2;
        this.leg4.rotateAngleX = MathHelper.cos(f1 * 0.6662F) * 1.4F * f2;
    }
}