// Date: 8/9/2013 8:07:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package claycorp.soggycarpet.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBear extends ModelBase
{
    // fields
    ModelRenderer snout;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer ear1;
    ModelRenderer ear2;

    public ModelBear()
    {
        textureWidth = 128;
        textureHeight = 64;
        System.out.println("DEBUG!!!!!! BEAR RENDERING");
        snout = new ModelRenderer(this, 0, 30);
        snout.addBox(0F, 0F, 0F, 4, 4, 4);
        snout.setRotationPoint(-2F, 8F, -18F);
        snout.setTextureSize(128, 64);
        snout.mirror = true;
        setRotation(snout, 0F, 0F, 0F);
        head = new ModelRenderer(this, 0, 0);
        head.addBox(-3F, -4F, -6F, 8, 8, 6);
        head.setRotationPoint(-1F, 9F, -8F);
        head.setTextureSize(128, 64);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body = new ModelRenderer(this, 18, 4);
        body.addBox(-6F, -10F, -7F, 18, 23, 15);
        body.setRotationPoint(-3F, 10F, 2F);
        body.setTextureSize(128, 64);
        body.mirror = true;
        setRotation(body, 1.570796F, 0F, 0F);
        leg1 = new ModelRenderer(this, 0, 16);
        leg1.addBox(-3F, 0F, -2F, 4, 7, 4);
        leg1.setRotationPoint(-5F, 17F, 12F);
        leg1.setTextureSize(128, 64);
        leg1.mirror = true;
        setRotation(leg1, 0F, 0F, 0F);
        leg2 = new ModelRenderer(this, 0, 16);
        leg2.addBox(1F, 0F, 1F, 4, 7, 4);
        leg2.setRotationPoint(3F, 17F, 9F);
        leg2.setTextureSize(128, 64);
        leg2.mirror = true;
        setRotation(leg2, 0F, 0F, 0F);
        leg3 = new ModelRenderer(this, 0, 16);
        leg3.addBox(-5F, 0F, -3F, 4, 7, 4);
        leg3.setRotationPoint(-3F, 17F, -5F);
        leg3.setTextureSize(128, 64);
        leg3.mirror = true;
        setRotation(leg3, 0F, 0F, 0F);
        leg4 = new ModelRenderer(this, 0, 16);
        leg4.addBox(1F, 0F, -3F, 4, 7, 4);
        leg4.setRotationPoint(3F, 17F, -5F);
        leg4.setTextureSize(128, 64);
        leg4.mirror = true;
        setRotation(leg4, 0F, 0F, 0F);
        ear1 = new ModelRenderer(this, 22, 0);
        ear1.addBox(-3.5F, -1.5F, -7.5F, 1, 1, 1);
        ear1.setRotationPoint(-1F, 6F, -7F);
        ear1.setTextureSize(128, 64);
        ear1.mirror = true;
        setRotation(ear1, 0F, 0F, 0F);
        ear2 = new ModelRenderer(this, 22, 0);
        ear2.addBox(4F, -4F, -4F, 1, 1, 1);
        ear2.setRotationPoint(-0.5F, 8.5F, -10.5F);
        ear2.setTextureSize(128, 64);
        ear2.mirror = true;
        setRotation(ear2, 0F, 0F, 0F);
    }

    @Override
    public void render(final Entity entity,
                       final float f,
                       final float f1,
                       final float f2,
                       final float f3,
                       final float f4,
                       final float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        snout.render(f5);
        head.render(f5);
        body.render(f5);
        leg1.render(f5);
        leg2.render(f5);
        leg3.render(f5);
        leg4.render(f5);
        ear1.render(f5);
        ear2.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float f,
                                  final float f1,
                                  final float f2,
                                  final float f3,
                                  final float f4,
                                  final float f5)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }
}