// Date: 8/14/2013 9:46:38 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package claycorp.wyldmod.entity.wizard;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWizard extends ModelBase
{
  //fields
    ModelRenderer Hat_Tip;
    ModelRenderer Hat_Curve_2;
    ModelRenderer Hat_Curve_1;
    ModelRenderer Hat_Base_2;
    ModelRenderer Hat_Base;
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Right_Arm;
    ModelRenderer Left_Arm;
    ModelRenderer Right_Leg;
    ModelRenderer Left_Leg;
    ModelRenderer Wand;
  
  public ModelWizard()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Hat_Tip = new ModelRenderer(this, 120, 14);
      Hat_Tip.addBox(0F, 0F, 0F, 2, 4, 2);
      Hat_Tip.setRotationPoint(-1F, -16F, 6F);
      Hat_Tip.setTextureSize(128, 64);
      Hat_Tip.mirror = true;
      setRotation(Hat_Tip, -1.099557F, 0F, 0F);
      Hat_Curve_2 = new ModelRenderer(this, 112, 20);
      Hat_Curve_2.addBox(0F, 0F, 0F, 4, 5, 4);
      Hat_Curve_2.setRotationPoint(-2F, -15F, 2F);
      Hat_Curve_2.setTextureSize(128, 64);
      Hat_Curve_2.mirror = true;
      setRotation(Hat_Curve_2, -0.6981317F, 0F, 0F);
      Hat_Curve_1 = new ModelRenderer(this, 104, 29);
      Hat_Curve_1.addBox(0F, 0F, 0F, 6, 5, 6);
      Hat_Curve_1.setRotationPoint(-3F, -12F, -2F);
      Hat_Curve_1.setTextureSize(128, 64);
      Hat_Curve_1.mirror = true;
      setRotation(Hat_Curve_1, -0.2792527F, 0F, 0F);
      Hat_Base_2 = new ModelRenderer(this, 96, 40);
      Hat_Base_2.addBox(0F, 0F, 0F, 8, 4, 8);
      Hat_Base_2.setRotationPoint(-4F, -8F, -4F);
      Hat_Base_2.setTextureSize(128, 64);
      Hat_Base_2.mirror = true;
      setRotation(Hat_Base_2, 0F, 0F, 0F);
      Hat_Base = new ModelRenderer(this, 88, 52);
      Hat_Base.addBox(-5F, 0F, 0F, 10, 2, 10);
      Hat_Base.setRotationPoint(0F, -4F, -5F);
      Hat_Base.setTextureSize(128, 64);
      Hat_Base.mirror = true;
      setRotation(Hat_Base, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 36);
      Head.addBox(-4F, -8F, -4F, 8, 8, 8);
      Head.setRotationPoint(0F, 4F, 0F);
      Head.setTextureSize(128, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 32, 48);
      Body.addBox(-4F, 0F, -2F, 8, 12, 4);
      Body.setRotationPoint(0F, 4F, 0F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Right_Arm = new ModelRenderer(this, 72, 50);
      Right_Arm.addBox(-3F, -2F, -2F, 4, 10, 4);
      Right_Arm.setRotationPoint(-5F, 6F, 0F);
      Right_Arm.setTextureSize(128, 64);
      Right_Arm.mirror = true;
      setRotation(Right_Arm, 0F, 0F, 0F);
      Left_Arm = new ModelRenderer(this, 56, 50);
      Left_Arm.addBox(-1F, -2F, -2F, 4, 10, 4);
      Left_Arm.setRotationPoint(5F, 6F, 0F);
      Left_Arm.setTextureSize(128, 64);
      Left_Arm.mirror = true;
      setRotation(Left_Arm, 0F, 0F, 0F);
      Right_Leg = new ModelRenderer(this, 16, 52);
      Right_Leg.addBox(-2F, 0F, -2F, 4, 8, 4);
      Right_Leg.setRotationPoint(-2F, 16F, 0F);
      Right_Leg.setTextureSize(128, 64);
      Right_Leg.mirror = true;
      setRotation(Right_Leg, 0F, 0F, 0F);
      Left_Leg = new ModelRenderer(this, 0, 52);
      Left_Leg.addBox(-2F, 0F, -2F, 4, 8, 4);
      Left_Leg.setRotationPoint(2F, 16F, 0F);
      Left_Leg.setTextureSize(128, 64);
      Left_Leg.mirror = true;
      setRotation(Left_Leg, 0F, 0F, 0F);
      Wand = new ModelRenderer(this, 0, 26);
      Wand.addBox(0F, 0F, 0F, 1, 1, 9);
      Wand.setRotationPoint(-6F, 12F, -9F);
      Wand.setTextureSize(128, 64);
      Wand.mirror = true;
      setRotation(Wand, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Hat_Tip.render(f5);
    Hat_Curve_2.render(f5);
    Hat_Curve_1.render(f5);
    Hat_Base_2.render(f5);
    Hat_Base.render(f5);
    Head.render(f5);
    Body.render(f5);
    Right_Arm.render(f5);
    Left_Arm.render(f5);
    Right_Leg.render(f5);
    Left_Leg.render(f5);
    Wand.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
