// Date: 8/11/2013 3:02:36 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package claycorp.soggycarpet.entity.bunny;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBunny extends ModelBase {
    // fields
    ModelRenderer body;
    ModelRenderer foot;
    ModelRenderer foot2;
    ModelRenderer head;
    ModelRenderer ear2;
    ModelRenderer ear;
    ModelRenderer tail;
    ModelRenderer nose;
    ModelRenderer frontleg2;
    ModelRenderer frontleg;

    public ModelBunny() {
        this.textureWidth = 32;
        this.textureHeight = 32;

        this.body = new ModelRenderer(this, 0, 0);
        this.body.addBox(0F, 0F, 0F, 7, 4, 4);
        this.body.setRotationPoint(-2.1F, 17F, -2F);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0F, 0F, 0.2792527F);
        this.foot = new ModelRenderer(this, 0, 0);
        this.foot.addBox(0F, 0F, 0F, 4, 2, 1);
        this.foot.setRotationPoint(-0.5F, 22F, 2F);
        this.foot.setTextureSize(64, 32);
        this.foot.mirror = true;
        this.setRotation(this.foot, 0F, 0.1396263F, 0F);
        this.foot2 = new ModelRenderer(this, 0, 0);
        this.foot2.addBox(0F, 0F, 0F, 4, 2, 1);
        this.foot2.setRotationPoint(-0.5F, 22F, -3F);
        this.foot2.setTextureSize(64, 32);
        this.foot2.mirror = true;
        this.setRotation(this.foot2, 0F, -0.1396263F, 0F);
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(0F, 0F, 0F, 2, 3, 3);
        this.head.setRotationPoint(-3.9F, 16F, -1.5F);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0F, 0F, 0.2792527F);
        this.ear2 = new ModelRenderer(this, 0, 0);
        this.ear2.addBox(0F, 0F, 0F, 1, 3, 1);
        this.ear2.setRotationPoint(-3.5F, 14F, -1.5F);
        this.ear2.setTextureSize(64, 32);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, 0F, 0F, 0.122173F);
        this.ear = new ModelRenderer(this, 0, 0);
        this.ear.addBox(0F, 0F, 0F, 1, 3, 1);
        this.ear.setRotationPoint(-3.5F, 14F, 0.5F);
        this.ear.setTextureSize(64, 32);
        this.ear.mirror = true;
        this.setRotation(this.ear, 0F, 0F, 0.122173F);
        this.tail = new ModelRenderer(this, 0, 0);
        this.tail.addBox(0F, 0F, 0F, 1, 2, 2);
        this.tail.setRotationPoint(4F, 19F, -1F);
        this.tail.setTextureSize(64, 32);
        this.tail.mirror = true;
        this.setRotation(this.tail, 0F, 0F, 0.2792527F);
        this.nose = new ModelRenderer(this, 0, 0);
        this.nose.addBox(0F, 0F, 0F, 1, 1, 1);
        this.nose.setRotationPoint(-4.5F, 17F, -0.5F);
        this.nose.setTextureSize(64, 32);
        this.nose.mirror = true;
        this.setRotation(this.nose, 0F, 0F, 0.2792527F);
        this.frontleg2 = new ModelRenderer(this, 0, 0);
        this.frontleg2.addBox(0F, 0F, 0F, 1, 4, 1);
        this.frontleg2.setRotationPoint(-2.5F, 20F, -2F);
        this.frontleg2.setTextureSize(64, 32);
        this.frontleg2.mirror = true;
        this.setRotation(this.frontleg2, 0F, 0F, 0.0174533F);
        this.frontleg = new ModelRenderer(this, 0, 0);
        this.frontleg.addBox(0F, 0F, 0F, 1, 4, 1);
        this.frontleg.setRotationPoint(-2.5F, 20F, 1F);
        this.frontleg.setTextureSize(64, 32);
        this.frontleg.mirror = true;
        this.setRotation(this.frontleg, 0F, 0F, 0.0174533F);
    }

    @Override
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.body.render(f5);
        this.foot.render(f5);
        this.foot2.render(f5);
        this.head.render(f5);
        this.ear2.render(f5);
        this.ear.render(f5);
        this.tail.render(f5);
        this.nose.render(f5);
        this.frontleg2.render(f5);
        this.frontleg.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        super.setRotationAngles(0.5F, 0.5F, f2, f3, f4, f5, null);
    }

}
