// Date: 8/14/2013 5:21:00 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package claycorp.wyldmod.entity.enderghast;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnderGhast extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer part;
    ModelRenderer part2;
    ModelRenderer part3;
    ModelRenderer part4;
    ModelRenderer part5;
    ModelRenderer part6;
    ModelRenderer part7;
    ModelRenderer part8;
    ModelRenderer part9;
    ModelRenderer part10;
    ModelRenderer part11;
    ModelRenderer part12;
    ModelRenderer part13;
  
  public ModelEnderGhast()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-16F, 0F, -16F, 32, 31, 32);
      Body.setRotationPoint(0F, -34F, 0F);
      Body.setTextureSize(512, 512);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      part = new ModelRenderer(this, 0, 0);
      part.addBox(0F, 0F, 0F, 2, 2, 15);
      part.setRotationPoint(-12F, -30F, 15F);
      part.setTextureSize(512, 512);
      part.mirror = true;
      setRotation(part, 0.2974289F, -0.4461433F, 0F);
      part2 = new ModelRenderer(this, 0, 0);
      part2.addBox(0F, 0F, 0F, 2, 2, 15);
      part2.setRotationPoint(-1F, -30F, 15F);
      part2.setTextureSize(512, 512);
      part2.mirror = true;
      setRotation(part2, 0.2974289F, 0F, 0F);
      part3 = new ModelRenderer(this, 0, 0);
      part3.addBox(0F, 0F, 0F, 2, 2, 15);
      part3.setRotationPoint(9F, -30F, 15F);
      part3.setTextureSize(512, 512);
      part3.mirror = true;
      setRotation(part3, 0.3346075F, 0.6320364F, 0.0743572F);
      part4 = new ModelRenderer(this, 0, 0);
      part4.addBox(0F, 0F, 0F, 2, 2, 15);
      part4.setRotationPoint(-12F, -19F, 15F);
      part4.setTextureSize(512, 512);
      part4.mirror = true;
      setRotation(part4, 0.1115358F, -0.4089647F, 0F);
      part5 = new ModelRenderer(this, 0, 0);
      part5.addBox(0F, 0F, 0F, 2, 2, 15);
      part5.setRotationPoint(-1F, -19F, 15F);
      part5.setTextureSize(512, 512);
      part5.mirror = true;
      setRotation(part5, -0.4089647F, -0.2230717F, 0F);
      part6 = new ModelRenderer(this, 0, 0);
      part6.addBox(0F, 0F, 0F, 2, 2, 15);
      part6.setRotationPoint(8.933333F, -19F, 15F);
      part6.setTextureSize(512, 512);
      part6.mirror = true;
      setRotation(part6, -0.1115358F, 0.2974289F, 0F);
      part7 = new ModelRenderer(this, 0, 0);
      part7.addBox(0F, 0F, 0F, 2, 2, 15);
      part7.setRotationPoint(-12F, -9F, 15F);
      part7.setTextureSize(512, 512);
      part7.mirror = true;
      setRotation(part7, -0.2974289F, -0.2974289F, 0F);
      part8 = new ModelRenderer(this, 0, 0);
      part8.addBox(0F, 0F, 0F, 2, 2, 15);
      part8.setRotationPoint(-1F, -9F, 15F);
      part8.setTextureSize(512, 512);
      part8.mirror = true;
      setRotation(part8, -0.3717861F, 0.1115358F, 0F);
      part9 = new ModelRenderer(this, 0, 0);
      part9.addBox(0F, 0F, 0F, 2, 2, 15);
      part9.setRotationPoint(9F, -9F, 15F);
      part9.setTextureSize(512, 512);
      part9.mirror = true;
      setRotation(part9, -0.2602503F, 0.4461433F, 0F);
      part10 = new ModelRenderer(this, 0, 0);
      part10.addBox(0F, 0F, 0F, 2, 2, 15);
      part10.setRotationPoint(4F, -14F, 15F);
      part10.setTextureSize(512, 512);
      part10.mirror = true;
      setRotation(part10, -0.2602503F, 0.2602503F, 0F);
      part11 = new ModelRenderer(this, 0, 0);
      part11.addBox(0F, 0F, 0F, 2, 2, 15);
      part11.setRotationPoint(-7F, -14F, 15F);
      part11.setTextureSize(512, 512);
      part11.mirror = true;
      setRotation(part11, -0.4833219F, -0.4089647F, 0F);
      part12 = new ModelRenderer(this, 0, 0);
      part12.addBox(0F, 0F, 0F, 2, 2, 15);
      part12.setRotationPoint(4F, -24F, 15F);
      part12.setTextureSize(512, 512);
      part12.mirror = true;
      setRotation(part12, 0.2230717F, 0.2602503F, 0F);
      part13 = new ModelRenderer(this, 0, 0);
      part13.addBox(0F, 0F, 0F, 2, 2, 15);
      part13.setRotationPoint(-7F, -24F, 15F);
      part13.setTextureSize(512, 512);
      part13.mirror = true;
      setRotation(part13, 0.1487144F, -0.2230717F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    part.render(f5);
    part2.render(f5);
    part3.render(f5);
    part4.render(f5);
    part5.render(f5);
    part6.render(f5);
    part7.render(f5);
    part8.render(f5);
    part9.render(f5);
    part10.render(f5);
    part11.render(f5);
    part12.render(f5);
    part13.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
