// Date: 8/14/2013 12:46:37 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package claycorp.soggycarpet.entity.shroom;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelShroom extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Cap1;
    ModelRenderer Cap2;
    ModelRenderer Cap3;
    ModelRenderer Cap4;
    ModelRenderer Eye2;
    ModelRenderer Eye1;
  
  public ModelShroom()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 49, 5);
      Body.addBox(0F, 0F, 0F, 8, 8, 8);
      Body.setRotationPoint(-4F, 16F, -4F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Cap1 = new ModelRenderer(this, 0, 46);
      Cap1.addBox(0F, 0F, 0F, 16, 2, 16);
      Cap1.setRotationPoint(-8F, 14F, -8F);
      Cap1.setTextureSize(128, 64);
      Cap1.mirror = true;
      setRotation(Cap1, 0F, 0F, 0F);
      Cap2 = new ModelRenderer(this, 0, 28);
      Cap2.addBox(0F, 0F, 0F, 14, 2, 14);
      Cap2.setRotationPoint(-7F, 12F, -7F);
      Cap2.setTextureSize(128, 64);
      Cap2.mirror = true;
      setRotation(Cap2, 0F, 0F, 0F);
      Cap3 = new ModelRenderer(this, 0, 14);
      Cap3.addBox(0F, 0F, 0F, 10, 2, 10);
      Cap3.setRotationPoint(-5F, 10F, -5F);
      Cap3.setTextureSize(128, 64);
      Cap3.mirror = true;
      setRotation(Cap3, 0F, 0F, 0F);
      Cap4 = new ModelRenderer(this, 0, 6);
      Cap4.addBox(0F, 0F, 0F, 4, 2, 4);
      Cap4.setRotationPoint(-2F, 8F, -2F);
      Cap4.setTextureSize(128, 64);
      Cap4.mirror = true;
      setRotation(Cap4, 0F, 0F, 0F);
      Eye2 = new ModelRenderer(this, 20, 3);
      Eye2.addBox(0F, 0F, 0F, 1, 4, 1);
      Eye2.setRotationPoint(1F, 18F, -4.5F);
      Eye2.setTextureSize(128, 64);
      Eye2.mirror = true;
      setRotation(Eye2, 0F, 0F, 0F);
      Eye1 = new ModelRenderer(this, 31, 3);
      Eye1.addBox(0F, 0F, 0F, 1, 4, 1);
      Eye1.setRotationPoint(-2F, 18F, -4.5F);
      Eye1.setTextureSize(128, 64);
      Eye1.mirror = true;
      setRotation(Eye1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Cap1.render(f5);
    Cap2.render(f5);
    Cap3.render(f5);
    Cap4.render(f5);
    Eye2.render(f5);
    Eye1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
